### ISSUE TITLE
SSLError: [Errno 2] _ssl.c:1413: The operation did not complete (read)

### ISSUE THREAD

**Issue by salzamt** [dgilland/pushjack#23]
hi, i am getting
`2016-10-19 02:00:06,879 ERROR: [Errno 2] _ssl.c:1413: The operation did not complete (read) [in /opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushfire_api/api/errors.py:18]
Traceback (most recent call last):
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushfire_api/api/views.py", line 76, in invalid_apns_tokens
    tokens = ps.get_expired_apns_tokens()
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushfire_api/push.py", line 130, in get_expired_apns_tokens
    tokens = self._get_apns_client().get_expired_tokens()
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushjack/apns.py", line 254, in get_expired_tokens
    tokens = list(APNSFeedbackStream(self.create_feedback_connection()))
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushjack/apns.py", line 619, in __iter__
    for chunk in self.conn.readchunks(4096):
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushjack/apns.py", line 347, in readchunks
    data = self.read(buffsize, timeout)
  File "/opt/pushfire-api/virtualenv/lib/python2.7/site-packages/pushjack/apns.py", line 333, in read
    chunk = self.client.read(buffsize - len(data))
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
SSLError: [Errno 2] _ssl.c:1413: The operation did not complete (read)`
when i am connecting to APNSFeedbackStream sometimes.
this happens on dev and production always on the first call, most of the times the second call works.
currently we built a workaround w/ retrying several times which seem to work for now.
any ideas what could cause this?

**Comment by dgilland** [comment]
Are you using anything to enhance/modify the underlying socket library, e.g., `gevent.monkey.patch_socket`?

**Comment by salzamt** [comment]
no, i found that problem quiet often to change patch_socket to patch_all but i am not using gevent. its a microservice which just uses python 2.7 w/ flask and push jack on ubuntu 12.04 and LXC.
any other idea? the workaround w/ just retrying helped but today even 5 retries failed :(
thanks

**Comment by dgilland** [comment]
What's the full version of the Python 2.7 that you're using?

**Comment by salzamt** [comment]
i am using 2.7.12 locally and production is 2.7.3 where it occurs on production more often for any reason, pretty much every second time i want to fetch.

**Comment by dgilland** [comment]
You may want to try upgrading your production version to the latest to see if that fixes things (unless you are also seeing the issue with 2.7.12?). I know there has been some changes/fixes to the SSL modules between 2.7.3 and 2.7.12 that may improve things.

**Comment by salzamt** [comment]
unfortunately those errors are occur in booth versions for us. also its only happening when getting the expired tokens from apns, everything else works fine. anything special on this apns fetch?

**Comment by dgilland** [comment]
The biggest difference is that the feedback reading using a larger buffer than when push errors are checked (4096 vs 6). It could be that instead of trying to read large chunks at a time (https://github.com/dgilland/pushjack/blob/master/pushjack/apns.py#L619), we should only try to read the expected length of the header, followed by the expected length of the tokens. The 2nd part is already being done so would just need modify the readchunks() approach and instead just read the header, get the token length, and then read the rest.

**Comment by dgilland** [comment]
I've made some small modifications on the [develop](https://github.com/dgilland/pushjack/tree/develop) branch to [optimize feedback reading](https://github.com/dgilland/pushjack/blob/0f285ac523add4720d3f180438534593455da8c7/pushjack/apns.py#L608).

Would you be able to install that version to see if it fixes the issue or not?

**Comment by salzamt** [comment]
thanks a lot, my colleague still has a local version and he takes over the testing, we will let you know!

**Comment by victorpantoja** [comment]
Hi @dgilland , I am @salzamt 's colleague. So, before testing develop branch, I tried to reproduced once again the error and I may have a good clue about it.

So as you can better understand, there are two applications involved:
- main application
- a microservice that sends out push notifications (the one @salzamt was talking about and has the error)

Main application connects hourly to the microservice to retrieve all invalid tokens and remove them from our database. Nothing special.

Well, I was having difficult to reproduce the error locally until I realised it could have something to do with this timeframe of 1 hour (hanging connections, memory leak, whatever). So, I started the microservice locally and could retrieve the tokens. Then, I wait 50 min before hitting the local microservice again and the error described by @salzamt occurred. I guess the problem would occur with less than 50 min as well.

So, I installed the develop branch and unfortunately the error still occurs but at least we now have a new clue.

**Comment by dgilland** [comment]
@victorpantoja, Thanks for checking. I've pushed another small change in 9f892e93844a752f842e18ad494a64f7b0492368 where the connection to the feedback service is explicitly closed after checking for expired tokens. Previously, it wasn't which could have resulted in an unclosed socket connection hanging around.

Can you report back if you're still having an issue after installing 9f892e93844a752f842e18ad494a64f7b0492368?

**Comment by victorpantoja** [comment]
@dgilland sorry for not answering before. I tested it but the problem is still happening.

**Comment by dgilland** [comment]
The only other thing I can think of is maybe Apple is abruptly closing the connection on it's end due to the frequency of feedback service requests. You could try increasing the interval between feedback requests to see if the issue goes away (e.g. increase from 1 hour to 2 hours, 2 hours to 4 hours, 4 hours to 8 hours, etc). It may be that Apple would like fewer requests per day. This is pure speculation on my part though.

**Comment by tablet-mode** [comment]
Hi, I'm working with @salzamt and @victorpantoja and recently we had the issue that this error occurred on every call to the feedback service despite only sending one request a day (with 10 retries, all of which failed for the same reason).

So I started playing around locally with our production cert and ran into the same issue: all my requests terminated with the error message mentioned earlier in this thread. At some point I tried to call self.read() with a smaller buffer size than 4096 and that worked. Since then everything seems to be working again. Not really sure what happened here but maybe it could provide a clue.

**Comment by dgilland** [comment]
I've release [v1.3.0](https://pypi.python.org/pypi/pushjack/1.3.0) which includes potential fixes for this. I'm going to go ahead and close this issue but if the problem still persists, feel free to re-open it with more details from the usage of the 1.3.0 version.

**Comment by tablet-mode** [comment]
@dgilland sounds great, thanks. We'll hopefully get around to testing it in a few days.
